### ISSUE TITLE
postgresql 设置的 db_name无效

### ISSUE THREAD

**Issue by wesley6j** [hexiaoyun128/ERP#3]
如果使用 postgres 数据库, db_name = "ERP" 这个不管怎么填, 最后都是用名字叫 `postgres` 的数据库.

相关设置:
```
db_type = "postgres"

#postgreSQL配置
[postgres]
db_alias = "default"
db_name = "ERP"
db_user = "postgres"
db_pwd = ""
db_host = "db"
db_port = 5432
db_sslmode = "disable"
```
pgweb 却只能这样连接:
`DATABASE_URL=postgres://postgres:@db:5432/postgres?sslmode=disable`

**Comment by itcloudy** [comment]
最后链接数据库的字符串打印出来看看，
